/* $Revision: 1.3 $ */
// Automatically generated by MATLAB Project Wizard version 1.0

//
// This is the gateway routine for a MATLAB Math/Graphics Library-based
// C MATLAB MEX File.

#include "mex.h"
#include "math.h"

double** RatioFeatures_Sample(double *B, double *C, int tam, int *N){
//Calcula o "Histogram ratio feature" de uma amostra.
    int x, y, n, cont;
    double **R;
    n = ((tam * tam) - tam)/2;
    *N = n;

    R = (double **) malloc (n * sizeof(double *));
    for (cont = 0; cont < n; cont++){
        R[cont] = (double *) malloc (3 * sizeof(double));
    }
    cont = -1;
    for(x = 0; x < tam; x++)
        for(y = x+1; y < tam; y++){
            cont++;
            R[cont][0] = B[x];
            R[cont][1] = B[y];
            R[cont][2] = C[x]/C[y];
        }
    return R;
}

int maior (int x, int y){
    if (x > y)
        return x;
    else
        return y;
}
void mexFunction(
	int nlhs,              // Number of left hand side (output) arguments
	mxArray *plhs[],       // Array of left hand side arguments
	int nrhs,              // Number of right hand side (input) arguments
	const mxArray *prhs[]  // Array of right hand side arguments
)
{
   double *B, *C, *pr, **R;
   int tam, col, lin, cont, N;

   /* check number of parameters */
   if (nrhs != 2) {
      mexErrMsgTxt("RatioFeatures_Sample_MEX requires two input argument.");
   } else if (nlhs != 1) {
      mexErrMsgTxt("RatioFeatures_Sample_MEX requires one output arguments.");
   }
//==========================================================================
   //Lê dados de B
   B = mxGetPr(prhs[0]);
   tam = maior(mxGetDimensions(prhs[0])[0], mxGetDimensions(prhs[0])[1]); /* nro de linha da matriz */
//==========================================================================
   //Lê dados de RSample
   C = mxGetPr(prhs[1]);
//==========================================================================
   R = RatioFeatures_Sample(B, C, tam, &N);
   //devolver pro matlab o resultado...
   plhs[0] = mxCreateDoubleMatrix(N,3,mxREAL);
   pr = (double *) mxGetPr(plhs[0]);
   cont = -1;
   for (col = 0; col < 3; col++){
	   for (lin = 0; lin < N; lin++){
		   cont++;
		   pr[cont] = R[lin][col];
	   }
   }
//==========================================================================
   //limpar variaveis...
   for (cont = 0; cont < N; cont++){
	   free(R[cont]);
   }
   free(R);
}
